const canvas = document.getElementById('aurora');
const ctx = canvas.getContext('2d');
let width = window.innerWidth.innerHeight;
      canvas.width = widxPoints = 40;xPoints = xPoints = 40;xPoints = 40;xPoints = 40;
                            this.life = 1;
                                                    }
                                                    
                                                                              update(mouseX, mouseY) {
                                                                                                            const last = this.points[this.points.length - 1];
                                                                                                                                              const dx = (mouseX - last.x) * 0.15;
                                                                                                                                                                                    const dy = (mouseY - last.y) * 0.15;
                                                                                                                                                                                                                              this.points.push({ x: last.x + dx, y: last.y + dy });
                                                                                                                                                                                                                                                                            if (this.points.length > this.maxPoints) this.points.shift();
                                                                                                                                                                                                                                                                                                                              this.life -= 0.005;
                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                        draw() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (this.points.length < 2 || this.life <= 0) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const gradient = ctx.createLinearGradient(year 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.points[0].x, this.points[0].y,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.points[this.points.length - 1].x,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.points[this.points.length - 1].y
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const color1 = `hsla(${hue}, 100%, 70%, ${this.life})`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const color2 = `hsla(${(hue + 80) % 360}, 100%, 60%, ${this.life})`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gradient.addColorStop(0, color1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          gradient.addColorStop(1, color2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.save();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.strokeStyle = gradient;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ctx.shadowBlur = 60;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.shadowColor = color2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.lineWidth = 18;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.globalAlpha = 0.4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ctx.beginPath();                                                       ctx.beginP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ctx.beginPath();
                                                                                                                                    ctx.moveTo(this.points[0].x, this.points[0].y);

                                                                                                                                        for (let i = 1; i < this.points.length; i++) {
                                                                                                                                              ctx.lineTo(this.points[i].x, this.points[i].y);
                                                                                                                                                  }

                                                                                                                                                      ctx.stroke();
                                                                                                                                                          ctx.restore();
                                                                                                                                                            }
                                                                                                                                                            }

                                                                                                                                                            let mouseX = width / 2;
                                                                                                                                                            let mouseY = height / 2;

                                                                                                                                                            document.addEventListener('mousemove', (e) => {
                                                                                                                                                              mouseX = e.clientX;
                                                                                                                                                                mouseY = e.clientY;
                                                                                                                                                                  if (ribbons.length < 8) ribbons.push(new Ribbon(mouseX, mouseY));
                                                                                                                                                                  });

                                                                                                                                                                  function animate() {
                                                                                                                                                                    ctx.fillStyle = 'rgba(0,0,0,0.12)';
                                                                                                                                                                      ctx.fillRect(0, 0, width, height);

                                                                                                                                                                        hue = (hue + 0.5) % 360;

                                                                                                                                                                          ribbons.forEach((ribbon, i) => {
                                                                                                                                                                              ribbon.update(mouseX, mouseY);
                                                                                                                                                                                  ribbon.draw();
                                                                                                                                                                                      if (ribbon.life <= 0) ribbons.splice(i, 1);
                                                                                                                                                                                        });

                                                                                                                                                                                          requestAnimationFrame(animate);
                                                                                                                                                                                          }

                                                                                                                                                                                          animate();

